### ISSUE TITLE
What changes are needed to `test.py`?

### ISSUE THREAD

**Issue by jgfoster** [PrairieLearn/pl-oer-python#5]
[questions/longestWord/tests/test.py](https://github.com/PrairieLearn/pl-oer-python/blob/master/questions/longestWord/tests/test.py) starts off with `#CHANGE THIS`. What changes are needed?

**Comment by mattoxb** [comment]
It is most likely from template code we used when mass-converting the code from one platform to another.  We can just remove that line.
